apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-container
          image: eureka-server-hskang:0.1
          ports:
            - containerPort: 8761
              name: eureka-server

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
  type: LoadBalancer

