apiVersion: apps/v1
kind: Deployment
metadata:
  name: produce-service
  labels:
    app: produce-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produce-service
  template:
    metadata:
      labels:
        app: produce-service
    spec:
      containers:
        - name: produce-service-container
          image: produce-service:0.1

---
apiVersion: v1
kind: Service
metadata:
  name: produce-service-cs
spec:
  selector:
    app: produce-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP

