server:
  port: 8082

spring:
  application:
    name: EurekaClient1

  kafka:
    bootstrap_servers: 127.0.0.1:9092
    template:
      default-topic: topic1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka-lb.hskang:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
